### Project specific config ###
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN="1"
    - COMPOSER_OAUTH_TOKEN="cc4a091c096e7d3cfe053c3f669fb840be60ab98"

matrix:
  include:
    - os: linux
      language: php
      php: 5.6
      env: ATOM_CHANNEL=stable
    - os: linux
      language: php
      php: 7.1
      env: ATOM_CHANNEL=beta

install:
  # Set the GitHub OAuth token for Composer
  - composer config -g github-oauth.github.com "$COMPOSER_OAUTH_TOKEN"
  - export PATH="$PATH:$HOME/.composer/vendor/bin"
  # Install PHPMD
  - composer global require "phpmd/phpmd"

before_script:
  - phpmd --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
