### Project specific config ###
env:
  global:
    - COMPOSER_DISABLE_XDEBUG_WARN="1"
    - secure: "fiJ/CO0SWd3PPnNbYEtgKxw2xa9fKTOx3qNK48joGEkYFngl5o18l8GlaCZo0wzjhdZdhopts0ZYejdyqRQgxA1QKfCG/Te0ukygRMPXBC+oSTY8fyCWnueZ0fF3O0wrDQUYUTLf8nPrFKOw7bOi0sn+Lcu3mUaWlGxrsHsg9GU="

matrix:
  include:
    - os: linux
      language: php
      php: 5.6
      env: ATOM_CHANNEL=stable
      install:
        # Set the GitHub OAuth token for Composer
        - composer config -g github-oauth.github.com "$COMPOSER_OAUTH_TOKEN"
        - export PATH="$PATH:$HOME/.composer/vendor/bin"
        # Install PHPMD
        - composer global require "phpmd/phpmd"

    - os: linux
      language: php
      php: 7.0
      env: ATOM_CHANNEL=beta
      install:
        # Set the GitHub OAuth token for Composer
        - composer config -g github-oauth.github.com "$COMPOSER_OAUTH_TOKEN"
        - export PATH="$PATH:$HOME/.composer/vendor/bin"
        # Install PHPMD
        - composer global require "phpmd/phpmd"

    - os: osx
      # Note: The OSX builds do not natively support PHP, so the order is swapped
      #  from the Linux builds.
      # Installed for linting the project
      language: generic
      env: ATOM_CHANNEL=stable
      install:
        # Install PHP 5.6
        - curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
        - export PATH="/usr/local/php5/bin:$PATH"
        # Install Composer
        - php -r "readfile('https://getcomposer.org/installer');" | sudo php -- --filename=composer
        - export PATH="$PATH:$HOME/.composer/vendor/bin"
        # Set the GitHub OAuth token for Composer
        - sudo php composer config -g github-oauth.github.com "$COMPOSER_OAUTH_TOKEN"
        # Install PHPMD
        - sudo php composer global require "phpmd/phpmd"

before_script:
  - phpmd --version

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
