### Project specific config ###
environment:
  COMPOSER_OAUTH_TOKEN:
    secure: PY0tnExp9ix66O1q0TuLbVwUg3YS6PIzFuI7B/3vUt8xPtLejPRlE4ewGTbgzmWH
  COMPOSER_DISABLE_XDEBUG_WARN: "1"

  matrix:
    - ATOM_CHANNEL: stable
    - ATOM_CHANNEL: beta

install:
  # Update Chocolatey
  - choco upgrade chocolatey -y
  # Enable Windows Update
  # This is required for one of the dependencies of the Chocolatey PHP package
  - sc config wuauserv start= auto
  - net start wuauserv
  # The following installs and sets up PHP
  - cinst -y php
  - cd c:\tools\php73
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - SET PATH=C:\tools\php73\;%PATH%
  # Install Composer
  - php -r "readfile('https://getcomposer.org/installer');" | php -- --filename=composer
  - ps: >-
      If (Test-Path variable:global:COMPOSER_OAUTH_TOKEN) {
        php composer config -g -- github-oauth.github.com "$Env:COMPOSER_OAUTH_TOKEN"
      }
  - SET PATH=%APPDATA%\Composer\vendor\bin;%PATH%
  # Install PHPMD
  - php composer global require "phpmd/phpmd"
  - phpmd --version

### Generic setup follows ###
build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

branches:
  only:
    - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
